version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: _database_name
      POSTGRES_USER: _username
      POSTGRES_PASSWORD: _password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U _username -d _database_name"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: